GET https://jsonplaceholder.typicode.com/todos

###

POST https://jsonplaceholder.typicode.com/todos
content-type: application/json

{
    "title": "sample"
}

###

DELETE https://jsonplaceholder.typicode.com/todos/1


